[package]
name = "frutta"
version = "0.1.0"
edition = "2021"

authors = ["dario lehy <dario.lehy@ik.me>"]

[workspace]
members = [
    "parser"
, "vm"]

[dependencies]
clap = {version="4.5.21", features=["derive"]}
parser = {path = "./parser"}
vm = {path = "vm" }

[profile.dev]
opt-level = 1
